version: 2.1

jobs:
  my_build:
    docker:
      - image: berliozcloud/circleci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Get my environment
          command: env
      - run:
          name: Check docker version
          command: docker --version
      - run:
          name: Run Build
          command: berlioz build

workflows:
  build:
    jobs:
      - my_build

