version: 2.1

jobs:

  deploy_to_prod:
    docker:
      - image: berliozcloud/circleci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Berlioz Login
          command: berlioz login --user $BERLIOZ_USER --pass $BERLIOZ_PASS
      - run:
          name: Run Build
          command: berlioz deploy --deployment gprod --region us-west1-c --wait

  undeploy:
    docker:
      - image: berliozcloud/circleci
    steps:
      - run:
          name: Check Status
          command: berlioz status --region us-west1-c --deployment gprod
      - run:
          name: Undeploy
          command: berlioz stop --region us-west1-c --deployment gprod --cluster addr
      - run:
          name: Wait completion
          command: berlioz wait --region us-west1-c --deployment gprod


workflows:

  deploy:
    jobs:
      - deploy_to_prod

  undeploy:
    jobs:
      - hold:
          type: approval
      - undeploy:
          requires: 
            - hold
