version: 2.1

jobs:
  deploy_to_prod:
    docker:
      - image: berliozcloud/circleci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Berlioz Login
          command: berlioz login --user $BERLIOZ_USER --pass $BERLIOZ_PASS
      - run:
          name: Run Build
          command: berlioz deploy --deployment gprod --region us-west1-c --wait

workflows:
  build:
    jobs:
      - deploy_to_prod

